version: '3.9'

services:
  db:
    image: postgres:16
    container_name: db_postgres_wallets
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data/

  wallet_app:
    build: .
    container_name: wallet_app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
